apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx-image
    imagePullPolicy: Never

# apiVersion: v1
# kind: Service
# metadata:
#   name: lb-nginx
# spec:
#   type: LoadBalancer
#   loadBalancerIP: 192.168.99.101
#   ports:
#     - port: 80
#       name: http
#       protocol: TCP
#       targetPort: 80
#   selector:
#     app: nginx

# ---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx-deployment
#   labels:
#     app: nginx
# spec:
#   replicas: 1
#   selector:
#     mathLabels:
#       app: nginx
#   template:
#     metadata:
#       labels:
#         app: nginx
#     spec:
#       containers:
#       - name: nginx
#         image: nginx-image
#         imagePullPolicy: Never
#         ports:
#           - containerPort: 80